version : "3"

services:
  bootnode:
    image: ethereum/client-go:alltools-stable
    command: bootnode --nodekey=/keys/boot.key -addr 0.0.0.0:30303
    volumes:
      - ./conf:/conf

  node:
    image: ethereum/client-go:alltools-stable
    depends_on:
      - bootnode
    command: sh /root/member.sh
    volumes:
      - ./conf:/conf
      - ./member.sh:/root/member.sh
